**Deep examine of the data quality**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../data/store-data-6aa6d7a3f171f140353680(1).csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10064 entries, 0 to 10063
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10064 non-null  int64
 1   Order ID       10064 non-null  str
 2   Order Date     10064 non-null  str
 3   Ship Date      9963 non-null   str
 4   Ship Mode      9763 non-null   str
 5   Customer ID    10064 non-null  str
 6   Customer Name  9713 non-null   str
 7   Segment        10064 non-null  str
 8   Country        10064 non-null  str
 9   City           10064 non-null  str
 10  State          10064 non-null  str
 11  Postal Code    9864 non-null   str
 12  Region         10064 non-null  str
 13  Product ID     10064 non-null  str
 14  Category       10064 non-null  str
 15  Sub-Category   10064 non-null  str
 16  Product Name   10064 non-null  str
 17  Sales          9863 non-null   float64
 18  Quantity       9865 non-null   float64
 19  Discount       10064 non-null  float64
 20  Profit         10064 non-null  float64
dtypes: float64(4), int64(1), str(16)
memory usage: 1.6 MB

**Customers**

In [10]:
df['Customer ID'].value_counts()

Customer ID
WB-21850    38
PP-18955    35
MA-17560    34
JL-15835    34
EH-13765    33
            ..
JR-15700     1
AO-10810     1
LD-16855     1
CJ-11875     1
RE-19405     1
Name: count, Length: 793, dtype: int64

In [13]:
df['Customer Name'].unique()

<StringArray>
[       'Claire Gute',    'Darrin Van Huff',     'Sean O'Donnell',
    'Brosina Hoffman',       'Andrew Allen',       'Irene Maddox',
      'Harold Pawlan',          'Pete Kriz',    'Alejandro Grove',
 'Zuschuss Donatelli',
 ...
     'NICK ZANDUSKY ',      'RICK BENSLEY ',    'FRANK CARLISLE ',
      'EMILY DUCICH ',        'JAY KIMMEL ',     'MICHELLE TRAN ',
       'TOBY RITTER ',        'BEN FERRER ',  'GIULIETTA DORTCH ',
       'DANA KAYDOS ']
Length: 811, dtype: str

**Check the categories**

In [ ]:
# with duplecates

df['Category'].value_counts()

Category
Office Supplies    5942
Furniture          2095
Technology         1826
office supplies     123
furniture            42
technology           36
Name: count, dtype: int64

In [ ]:
# with no duplecates

df.drop_duplicates()['Category'].value_counts()

Category
Office Supplies    5927
Furniture          2085
Technology         1817
office supplies     123
furniture            42
technology           36
Name: count, dtype: int64

**Check for missing Values**

In [32]:
m_names = len(df) - df['Customer Name'].count()
m_Postal_codes = len(df) - df['Postal Code'].count()
m_sales = len(df) - df['Sales'].count()
m_quantity = len(df) - df['Quantity'].count()
m_ship_mode = len(df) - df['Ship Mode'].count()
m_ship_date = len(df) - df['Ship Date'].count()

print(f"[+] missing Customer Name : {m_names}\n[+] missing Postal Codes : {m_Postal_codes}\n[+] missing Sales : {m_sales}\n[+] missing Quantity : {m_quantity}\n[+] missing Ship Mode : {m_ship_mode}\n[+] missing Ship Date : {m_ship_date}")

[+] missing Customer Name : 351
[+] missing Postal Codes : 200
[+] missing Sales : 201
[+] missing Quantity : 199
[+] missing Ship Mode : 301
[+] missing Ship Date : 101

**Check for the duplicated rows**

In [73]:
# df[df.duplicated()].head(5)
# df[df.duplicated()].sort_values('Row ID', ascending=False)
df.loc[df['Row ID'] == 1442]
# df.sort_values('Row ID', ascending=False)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1441,1442,CA-2017-128160,12/19/2017,12/24/2017,Second Class,MM-17920,NaN,Consumer,United States,San Francisco,...,94110.0,West,OFF-BI-10001510,Office Supplies,Binders,Deluxe Heavy-Duty Vinyl Round Ring Binder,NaN,2.0,0.2,11.46
9995,1442,CA-2017-128160,12/19/2017,12/24/2017,Second Class,MM-17920,NaN,Consumer,United States,San Francisco,...,94110.0,West,OFF-BI-10001510,Office Supplies,Binders,Deluxe Heavy-Duty Vinyl Round Ring Binder,NaN,2.0,0.2,11.46

**Check for minimum / maximum / meadian / mean**

In [40]:
df.describe()

             Row ID         Sales     Quantity      Discount        Profit
count  10064.000000  9.863000e+03  9865.000000  10064.000000  10064.000000
mean    4994.397059  1.950322e+03     3.780233      0.157501     28.571309
std     2885.848580  4.410673e+04     2.240134      0.210586    233.509461
min        1.000000  4.440000e-01    -5.000000      0.000000  -6599.978000
25%     2496.750000  1.729000e+01     2.000000      0.000000      1.724800
50%     4989.500000  5.450000e+01     3.000000      0.200000      8.643600
75%     7494.250000  2.107600e+02     5.000000      0.200000     29.331600
max     9994.000000  1.131924e+06    14.000000      1.500000   8399.976000

**Sales**

In [47]:
s_mean = df['Sales'].mean()
s_min = df['Sales'].min()
s_max = df['Sales'].max()
s_median = df['Sales'].median()

print(f"[+] Sales Mean : {s_mean}\n"f"[+] Sales Min : {s_min}\n"f"[+] Sales Max : {s_max}\n"f"[+] Sales Median : {s_median}")

[+] Sales Mean : 1950.3220962486057
[+] Sales Min : 0.444
[+] Sales Max : 1131924.0
[+] Sales Median : 54.5

**Quantity**

In [48]:
q_mean = df['Quantity'].mean()
q_min = df['Quantity'].min()
q_max = df['Quantity'].max()
q_median = df['Quantity'].median()


print(f"[+] Quantity Mean : {q_mean}\n[+] Quantity Min : {q_min}\n[+] Quantity Max : {q_max}\n[+] Quantity Median : {q_median}")

[+] Quantity Mean : 3.7802331474911304
[+] Quantity Min : -5.0
[+] Quantity Max : 14.0
[+] Quantity Median : 3.0

**Discount**

In [51]:
d_mean = df['Discount'].mean()
d_min = df['Discount'].min()
d_max = df['Discount'].max()
d_median = df['Discount'].median()

print(f"[+] Discount Mean : {d_mean}\n[+] Discount Min : {d_min}\n[+] Discount Max : {d_max}\n[+] Discount Median : {d_median}")

[+] Discount Mean : 0.15750099364069953
[+] Discount Min : 0.0
[+] Discount Max : 1.5
[+] Discount Median : 0.2

In [ ]:
num_nulls_threshold = 2
filtered_rows = df[df.isnull().sum(axis=1) >= num_nulls_threshold]
# filtered_rows['']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
96,97,CA-2017-161018,11/9/2017,11/11/2017,Second Class,PN-18775,NaN,Home Office,United States,New York City,...,10009.0,East,FUR-FU-10000629,Furniture,Furnishings,9-3/4 Diameter Round Wall Clock,NaN,7.0,0.0,40.5426
157,158,CA-2014-104269,3/1/2014,NaN,Second Class,DB-13060,Dave Brooks,Consumer,United States,Seattle,...,98115.0,West,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,457.568,NaN,0.2,51.4764
345,346,CA-2017-169901,6/15/2017,6/19/2017,Standard Class,CC-12550,Clay Cheatham,Consumer,United States,San Francisco,...,94122.0,West,TEC-PH-10002293,Technology,Phones,Anker 36W 4-Port USB Wall Charger Travel Power...,NaN,NaN,0.2,4.7976
347,348,CA-2017-134306,7/8/2017,7/12/2017,Standard Class,TD-20995,Tamara Dahlen,Consumer,United States,Lowell,...,1852.0,East,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,NaN,NaN,0.0,11.5432
385,386,US-2015-168935,11/27/2015,12/2/2015,NaN,DO-13435,Denny Ordway,Consumer,United States,Pembroke Pines,...,NaN,South,TEC-AC-10002335,Technology,Accessories,Logitech Media Keyboard K200,83.976,3.0,0.2,-1.0497
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1442,CA-2017-128160,12/19/2017,12/24/2017,Second Class,MM-17920,NaN,Consumer,United States,San Francisco,...,94110.0,West,OFF-BI-10001510,Office Supplies,Binders,Deluxe Heavy-Duty Vinyl Round Ring Binder,NaN,2.0,0.2,11.4600
10016,4904,CA-2017-110884,3/7/2017,3/12/2017,NaN,SH-20395,NaN,Consumer,United States,New York City,...,10035.0,East,OFF-LA-10003510,office supplies,Labels,Avery 4027 File Folder Labels for Dot Matrix P...,91.590,3.0,0.0,42.1314
10023,734,CA-2017-131954,1/21/2017,1/25/2017,Standard Class,DS-13030,NaN,Home Ofice,United States,Seattle,...,98115.0,West,TEC-AC-10003610,Technology,Accessories,Logitech Illuminated - Keyboard,NaN,3.0,0.0,86.3856
10033,9240,CA-2017-110310,10/27/2017,1/1/2010,NaN,NB-18655,NaN,Corporate,United States,Tallahassee,...,32303.0,South,OFF-PA-10001685,Office Supplies,Paper,Easy-staple paper,56.784,7.0,0.2,20.5842
10037,9044,CA-2016-168830,11/7/2016,11/13/2016,Standard Class,ML-17395,NaN,Corporate,United States,San Francisco,...,NaN,West,TEC-AC-10003911,Technology,Accessories,NETGEAR AC1750 Dual Band Gigabit Smart WiFi Ro...,479.970,3.0,0.0,163.1898