In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import hashlib

df = pd.read_csv('../data/store-data-6aa6d7a3f171f140353680(1).csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10064 entries, 0 to 10063
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10064 non-null  int64
 1   Order ID       10064 non-null  str
 2   Order Date     10064 non-null  str
 3   Ship Date      9963 non-null   str
 4   Ship Mode      9763 non-null   str
 5   Customer ID    10064 non-null  str
 6   Customer Name  9713 non-null   str
 7   Segment        10064 non-null  str
 8   Country        10064 non-null  str
 9   City           10064 non-null  str
 10  State          10064 non-null  str
 11  Postal Code    9864 non-null   str
 12  Region         10064 non-null  str
 13  Product ID     10064 non-null  str
 14  Category       10064 non-null  str
 15  Sub-Category   10064 non-null  str
 16  Product Name   10064 non-null  str
 17  Sales          9863 non-null   float64
 18  Quantity       9865 non-null   float64
 19  Discount       10064 non-null  float64
 20  Profit         10064 non-null  float64
dtypes: float64(4), int64(1), str(16)
memory usage: 1.6 MB

In [2]:
df = df.drop_duplicates()

In [3]:
df[df.duplicated()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [4]:
df.loc[df['Order Date'] > df['Ship Date'] ].head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2.0,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3.0,0.0,219.5820
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7.0,0.0,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4.0,0.0,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6.0,0.2,90.7152

In [5]:
df.loc[df['Postal Code'].isnull()].head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
53,54,CA-2016-105816,12/11/2016,12/17/2016,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,...,NaN,East,OFF-FA-10000304,Office Supplies,Fasteners,Advantus Push Pins,15.260,7.0,0.0,6.2566
75,76,US-2017-118038,12/9/2017,12/11/2017,First Class,KB-16600,Ken Brennan,Corporate,United States,Houston,...,NaN,Central,OFF-BI-10004182,Office Supplies,Binders,Economy Binders,1.248,3.0,0.8,-1.9344
93,94,CA-2015-149587,1/31/2015,2/5/2015,Second Class,KB-16315,Karl Braun,Consumer,United States,Minneapolis,...,NaN,Central,FUR-FU-10003799,Furniture,Furnishings,"Seth Thomas 13 1/2"" Wall Clock",53.340,3.0,0.0,16.5354
118,119,US-2015-136476,4/5/2015,4/10/2015,Standard Class,GG-14650,Greg Guthrie,Corporate,United States,Bristol,...,NaN,South,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,157.794,1.0,0.7,-115.7156
141,142,CA-2017-106180,9/18/2017,9/23/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,San Francisco,...,NaN,West,OFF-AR-10000940,Office Supplies,Art,Newell 343,8.820,3.0,0.0,2.3814

In [6]:
# df = df.loc[df['City'] == 'Minneapolis', 'Postal Code'].fillna(55407.0)
# df['Postal Code'] = np.where(df['City'] == 'Minneapolis', 55407.0, df['Postal Code'])
# df.loc[df['City'] == 'Minneapolis', ['Postal Code']].isnull()

df.loc[(df['City'] == 'New York City') & (df['Postal Code'].notnull())].head(5)

# df['Postal code'].filna('55407.0')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
54,55,CA-2016-105816,12/11/2016,NaN,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,...,10024.0,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950,5.0,0.0,298.6855
70,71,CA-2016-106075,9/18/2016,9/23/2016,Standard Class,HM-14980,Henry MacAllister,Consumer,United States,New York City,...,10009.0,East,OFF-BI-10004654,Office Supplies,Binders,Avery Binding System Hidden Tab Executive Styl...,4.616,1.0,0.2,1.7310
96,97,CA-2017-161018,11/9/2017,11/11/2017,Second Class,PN-18775,NaN,Home Office,United States,New York City,...,10009.0,East,FUR-FU-10000629,Furniture,Furnishings,9-3/4 Diameter Round Wall Clock,NaN,7.0,0.0,40.5426
110,111,CA-2017-146780,12/25/2017,12/30/2017,Standard Class,CV-12805,Cynthia Voltz,Corporate,United States,New York City,...,10035.0,East,FUR-FU-10001934,Furniture,Furnishings,Magnifier Swing Arm Lamp,41.960,2.0,0.0,10.9096
179,180,CA-2015-137225,12/15/2015,12/19/2015,Standard Class,JK-15640,Jim Kriz,Home Office,United States,New York City,...,10009.0,East,OFF-AR-10001940,Office Supplies,Art,"Sanford Colorific Eraseable Coloring Pencils, ...",3.280,1.0,0.0,1.4104

**standardizing City names**

In [7]:
df['City'] = df['City'].str.title()

**Filling the missing Postal codes**

In [8]:
mode_dict = (
    df.dropna(subset=['Postal Code']).value_counts(['City', 'Postal Code']).reset_index().drop_duplicates('City').set_index('City')['Postal Code'].to_dict())


get_null_idx = df[df['Postal Code'].isna()].index

for idx in get_null_idx:
    city = df.at[idx, 'City']
    if city in mode_dict:
        df.at[idx, 'Postal Code'] = mode_dict[city]



df.loc[df['Postal Code'].isna()]
# df.info()



# df[df['City']== '']

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [9]:
df[df['Ship Mode'].isna()]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
28,29,US-2015-150630,9/17/2015,9/21/2015,NaN,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140.0,East,OFF-BI-10000474,Office Supplies,Binders,Avery Recycled Flexi-View Covers for Binding S...,9.618,2.0,0.7,-7.0532
94,95,CA-2015-149587,1/31/2015,2/5/2015,NaN,KB-16315,Karl Braun,Consumer,United States,Minneapolis,...,55407.0,Central,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,32.960,2.0,0.0,16.1504
191,192,CA-2015-102281,10/12/2015,10/14/2015,NaN,MP-17470,Mark Packer,Home Office,United States,New York City,...,10035.0,East,OFF-PA-10000061,Office Supplies,Paper,Xerox 205,51.840,8.0,0.0,24.8832
252,253,CA-2016-146941,12/10/2016,12/13/2016,NaN,DL-13315,Delfina Latchford,Consumer,United States,New York City,...,10024.0,East,OFF-ST-10001228,Office Supplies,Storage,"Fellowes Personal Hanging Folder Files, Navy",80.580,6.0,0.0,22.5624
314,315,CA-2014-167850,8/9/2014,8/16/2014,NaN,AG-10525,Andy Gerbode,Corporate,United States,Saint Petersburg,...,33710.0,South,TEC-PH-10002398,Technology,Phones,AT&T 1070 Corded Phone,178.384,2.0,0.2,22.2980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9911,9912,US-2014-157231,4/5/2014,4/9/2014,NaN,RP-19855,Roy Phan,Corporate,United States,Richmond,...,40475.0,South,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,115.360,7.0,0.0,56.5264
9964,9965,CA-2016-146374,12/5/2016,12/10/2016,NaN,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711.0,East,FUR-FU-10002671,Furniture,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,13.400,1.0,0.0,6.4320
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,NaN,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2.0,0.0,72.9480
10016,4904,CA-2017-110884,3/7/2017,3/12/2017,NaN,SH-20395,NaN,Consumer,United States,New York City,...,10035.0,East,OFF-LA-10003510,office supplies,Labels,Avery 4027 File Folder Labels for Dot Matrix P...,91.590,3.0,0.0,42.1314
10033,9240,CA-2017-110310,10/27/2017,1/1/2010,NaN,NB-18655,NaN,Corporate,United States,Tallahassee,...,32303.0,South,OFF-PA-10001685,Office Supplies,Paper,Easy-staple paper,56.784,7.0,0.2,20.5842

In [10]:
df[df['Customer ID'] == 'TB-21520']['Ship Mode'].mode()

0    Standard Class
Name: Ship Mode, dtype: str

**Filling the missing Ship mode**

In [11]:
df.value_counts(['Customer ID', 'Ship Mode'])

Customer ID  Ship Mode
EH-13765     Standard Class    26
ZC-21910     Standard Class    25
EP-13915     Standard Class    24
SH-19975     Standard Class    23
XP-21865     Standard Class    23
                               ..
CP-12340     Second Class       1
RD-19660     Second Class       1
CL-12700     Second Class       1
AS-10240     Same Day           1
SW-20455     Second Class       1
Name: count, Length: 2035, dtype: int64

In [ ]:

mode_dict = (
    df.dropna(subset=['Ship Mode']).value_counts(['Customer ID', 'Ship Mode']).reset_index().drop_duplicates('Customer ID').set_index('Customer ID')['Ship Mode'].to_dict()
    )


# print(mode_dict)

get_null_idx = df[df['Ship Mode'].isna()].index

for idx in get_null_idx:
    customer = df.at[idx, 'Customer ID']
    if customer in mode_dict:
        df.at[idx, 'Ship Mode'] = mode_dict[customer]

In [83]:
w =df.value_counts(['Customer ID', 'Ship Mode']).reset_index()


w['count']

0       26
1       25
2       24
3       23
4       23
        ..
2030     1
2031     1
2032     1
2033     1
2034     1
Name: count, Length: 2035, dtype: int64

In [13]:
df[df['Ship Mode'].isna()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

**Filling the missing Customer Name**

In [14]:
df[df['Customer Name'].isna()]
# df[df['Customer ID'] == 'TB-21520']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
29,30,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,NaN,Consumer,United States,Philadelphia,...,19140.0,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.200,3.0,0.2,15.5250
31,32,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,NaN,Consumer,United States,Philadelphia,...,19140.0,East,OFF-AR-10004042,Office Supplies,Art,"BOSTON Model 1800 Electric Pencil Sharpeners, ...",86.304,6.0,0.2,9.7092
33,34,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,NaN,Consumer,United States,Philadelphia,...,19140.0,East,OFF-AR-10001683,Office Supplies,Art,Lumber Crayons,15.760,2.0,0.2,3.5460
35,36,CA-2016-117590,12/8/2016,12/10/2016,First Class,GH-14485,NaN,Corporate,United States,Richardson,...,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7.0,0.2,123.4737
39,40,CA-2015-117415,12/27/2015,12/31/2015,Standard Class,SN-20710,NaN,Home Office,United States,Houston,...,77041.0,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",212.058,3.0,0.3,-15.1470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10031,6743,US-2017-101784,7/6/2017,7/11/2017,Standard Class,PO-18850,NaN,Consumer,United States,Los Angeles,...,90008.0,West,FUR-CH-10001146,Furniture,Chairs,"Global Task Chair, Black",122.136,3.0,0.2,-13.7403
10033,9240,CA-2017-110310,10/27/2017,1/1/2010,First Class,NB-18655,NaN,Corporate,United States,Tallahassee,...,32303.0,South,OFF-PA-10001685,Office Supplies,Paper,Easy-staple paper,56.784,7.0,0.2,20.5842
10034,6120,CA-2017-143378,9/19/2017,9/25/2017,Standard Class,JR-16210,NaN,Corporate,United States,Springfield,...,97477.0,West,OFF-AR-10001915,Office Supplies,Art,Peel-Off China Markers,23.832,3.0,0.2,6.5538
10036,2996,US-2014-150532,7/14/2014,7/21/2014,Standard Class,PB-19150,NaN,Consumerr,United States,Phoenix,...,85023.0,West,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,55.920,5.0,0.2,6.2910
10062,4962,CA-2014-156587,3/7/2014,3/8/2014,First Class,AB-10015,NaN,Consumer,United States,Seattle,...,98103.0,West,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1.0,0.2,5.4801

In [15]:
mode_dict = (
    df.dropna(subset=['Customer Name']).value_counts(['Customer ID', 'Customer Name']).reset_index().drop_duplicates('Customer ID').set_index('Customer ID')['Customer Name'].to_dict()
    )

print(mode_dict)


get_null_idx = df[df['Customer Name'].isna()].index

for idx in get_null_idx:
    customer = df.at[idx, 'Customer ID']
    if customer in mode_dict:
        df.at[idx, 'Customer Name'] = mode_dict[customer]

{'WB-21850': 'William Brown', 'JL-15835': 'John Lee', 'PP-18955': 'Paul Prost', 'MA-17560': 'Matt Abelman', 'JD-15895': 'Jonathan Doherty', 'CK-12205': 'Chloris Kastensmidt', 'SV-20365': 'Seth Vernon', 'EH-13765': 'Edward Hooks', 'EP-13915': 'Emily Phan', 'AP-10915': 'Arthur Prichep', 'LC-16870': 'Lena Cacioppo', 'KL-16645': 'Ken Lonsdale', 'GT-14710': 'Greg Tran', 'BM-11650': 'Brian Moss', 'Dp-13240': 'Dean percer', 'CL-12565': 'Clay Ludtke', 'XP-21865': 'Xylona Preis', 'KD-16495': 'Keith Dawkins', 'KM-16720': 'Kunst Miller', 'SH-19975': 'Sally Hughsby', 'ZC-21910': 'Zuschuss Carroll', 'BF-11170': 'Ben Ferrer', 'CB-12025': 'Cassandra Brandow', 'CS-12250': 'Chris Selesnick', 'PG-18820': 'Patrick Gardner', 'DK-12835': 'Damala Kotsonis', 'PK-19075': 'Pete Kriz', 'SC-20725': 'Steven Cartwright', 'EA-14035': 'Erin Ashbrook', 'CK-12595': 'Clytie Kelty', 'NS-18640': 'Noel Staavos', 'BH-11710': 'Brosina Hoffman', 'GG-14650': 'Greg Guthrie', 'DR-12880': 'Dan Reichenbach', 'LA-16780': 'Laura Armstrong', 'SJ-20125': 'Sanjit Jacobs', 'RP-19390': 'Resi Pölking', 'SP-20620': 'Stefania Perrino', 'AS-10090': 'Adam Shillingsburg', 'SV-20785': 'Stewart Visinsky', 'LB-16795': 'Laurel Beltran', 'SP-20860': 'Sung Pak', 'KH-16510': 'Keith Herrera', 'RL-19615': 'Rob Lucas', 'MS-17365': 'Maribeth Schnelling', 'JA-15970': 'Joseph Airdo', 'RW-19540': 'Rick Wilson', 'DH-13075': 'Dave Hallsten', 'AH-10690': 'Anna Häberlin', 'KB-16585': 'Ken Black', 'JE-15745': 'Joel Eaton', 'RB-19465': 'Rick Bensley', 'LC-16885': 'Lena Creighton', 'KL-16555': 'Kelly Lampkin', 'RA-19915': 'Russell Applegate', 'SC-20095': 'Sanjit Chand', 'CS-11950': 'Carlos Soltero', 'GA-14725': 'Guy Armstrong', 'CS-12355': 'Christine Sundaresam', 'CC-12220': 'Chris Cortes', 'AM-10705': 'Anne McFarland', 'DK-13375': 'Dennis Kane', 'IM-15070': 'Irene Maddox', 'LS-16975': 'Lindsay Shagiari', 'RD-19900': 'Ruben Dartt', 'PO-18850': "Patrick O'Brill", 'SA-20830': 'Sue Ann Reed', 'DB-13210': 'Dean Braden', 'NP-18325': 'Naresj Patel', 'FH-14275': 'Frank Hawley', 'SM-20950': 'Suzanne McNair', 'ME-17320': 'Maria Etezadi', 'MY-18295': 'Muhammed Yedwab', 'NW-18400': 'Natalie Webber', 'PS-18760': 'Pamela Stobb', 'JE-15715': 'Joe Elijah', 'EM-14140': 'Eugene Moren', 'ES-14080': 'Erin Smith', 'KB-16315': 'Karl Braun', 'FM-14290': 'Frank Merwin', 'AG-10495': 'Andrew Gjertsen', 'BP-11095': 'Bart Pistole', 'SS-20140': 'Saphhira Shifley', 'SD-20485': 'Shirley Daniels', 'BB-11545': 'Brenda Bowman', 'BD-11605': 'Brian Dahlen', 'AJ-10795': 'Anthony Johnson', 'JK-15730': 'Joe Kamberova', 'GB-14530': 'George Bell', 'KM-16375': 'Katherine Murray', 'AB-10105': 'Adrian Barton', 'EB-13750': 'Edward Becker', 'BT-11680': 'Brian Thompson', 'SC-20380': 'Shahid Collister', 'DM-13015': 'Darrin Martin', 'RD-19720': 'Roger Demir', 'SC-20770': 'Stewart Carmichael', 'MB-17305': 'Maria Bertelson', 'LC-17140': 'Logan Currie', 'DS-13180': 'David Smith', 'LH-17155': 'Logan Haushalter', 'CB-12535': 'Claudia Bergmann', 'AG-10900': 'Arthur Gainer', 'DK-13225': 'Dean Katz', 'CJ-12010': 'Caroline Jumper', 'MP-17965': 'Michael Paige', 'CC-12430': 'Chuck Clark', 'BF-11020': 'Barry Französisch', 'HW-14935': 'Helen Wasserman', 'SE-20110': 'Sanjit Engle', 'AP-10720': 'Anne Pryor', 'HM-14860': 'Harry Marie', 'MS-17770': 'Maxwell Schwartz', 'MC-18100': 'Mick Crebagga', 'ML-17395': 'Marina Lichtenstein', 'MM-18055': 'Michelle Moray', 'JM-16195': 'Justin MacKendrick', 'TB-21250': 'Tim Brockman', 'PF-19120': 'Peter Fuller', 'SN-20710': 'Steve Nguyen', 'TB-21055': 'Ted Butterfield', 'CV-12805': 'Cynthia Voltz', 'VW-21775': 'Victoria Wilson', 'NZ-18565': 'Nick Zandusky', 'TS-21205': 'Thomas Seio', 'AB-10060': 'Adam Bellavance', 'RB-19795': 'Ross Baird', 'BD-11320': 'Bill Donatelli', 'EH-14125': 'Eugene Hildebrand', 'DS-13030': 'Darrin Sayre', 'AH-10075': 'Adam Hart', 'KM-16225': 'Kalyca Meade', 'MH-18115': 'Mick Hernandez', 'DC-12850': 'Dan Campbell', 'JF-15190': 'Jamie Frazer', 'SZ-20035': 'Sam Zeldin', 'AI-10855': 'Arianne Irving', 'MP-18175': 'Mike Pelletier', 'JE-15610': 'Jim Epp', 'KH-16330': 'Katharine Harms', 'CT-11995': 'Carol Triggs', 'TM-21010': 'Tamara Manning', 'SU-20665': 'Stephanie Ulpright', 'AA-10645': 'Anna Andreadi', 'EH-13945': 'Eric Hoffmann', 'TB-21520': 'Tracy Blumstein', 'DP-13000': 'Darren Powers', 'PG-18895': 'Paul Gonzalez', 'JM-15250': 'Janet Martin', 'HA-14920': 'Helen Andreada', 'BP-11185': 'Ben Peterman', 'FA-14230': 'Frank Atkinson', 'JL-15505': 'Jeremy Lonsdale', 'MK-17905': 'Michael Kennedy', 'RB-19360': 'Raymond Buch', 'MD-17350': 'Maribeth Dona', 'BN-11515': 'Bradley Nguyen', 'MC-17605': 'Matt Connell', 'CA-12775': 'Cynthia Arntzen', 'BW-11110': 'Bart Watters', 'RD-19585': 'Rob Dowd', 'ND-18370': 'Natalie DeCherney', 'TB-21400': 'Tom Boeckenhauer', 'JG-15160': 'James Galang', 'HF-14995': 'Herbert Flentye', 'JS-16030': 'Joy Smith', 'MC-17590': 'Matt Collister', 'KF-16285': 'Karen Ferguson', 'BC-11125': 'Becky Castell', 'SC-20260': 'Scott Cohen', 'GH-14410': 'Gary Hansen', 'SC-20020': 'Sam Craven', 'BM-11140': 'Becky Martin', 'JB-15400': 'Jennifer Braxton', 'VD-21670': 'Valerie Dominguez', 'DL-13315': 'Delfina Latchford', 'SB-20290': 'Sean Braxton', 'TD-20995': 'Tamara Dahlen', 'JP-15520': 'Jeremy Pistek', 'LR-16915': 'Lena Radford', 'NB-18655': 'Nona Balk', 'NG-18355': 'Nat Gilpin', 'AT-10735': 'Annie Thurman', 'JD-16150': 'Justin Deggeller', 'RA-19285': 'Ralph Arnett', 'JK-15370': 'Jay Kimmel', 'RD-19810': 'Ross DeVincentis', 'JF-15355': 'Jay Fein', 'RW-19630': 'Rob Williams', 'TS-21160': 'Theresa Swint', 'NC-18340': 'Nat Carroll', 'HG-14965': 'Henry Goldwyn', 'BP-11290': 'Beth Paige', 'CA-12265': 'Christina Anderson', 'KN-16390': 'Katherine Nockton', 'JC-15775': 'John Castell', 'AC-10615': 'Ann Chong', 'AH-10120': 'Adrian Hane', 'RF-19345': 'Randy Ferguson', 'RB-19435': 'Richard Bierner', 'EM-13825': 'Elizabeth Moffitt', 'GB-14575': 'Giulietta Baptist', 'SO-20335': "Sean O'Donnell", 'RA-19885': 'Ruben Ausman', 'LH-16900': 'Lena Hernandez', 'KD-16270': 'Karen Daniels', 'SP-20650': 'Stephanie Phelps', 'HK-14890': 'Heather Kirkland', 'AG-10675': 'Anna Gayman', 'KH-16630': 'Ken Heidel', 'PO-19180': 'Philisse Overcash', 'AA-10375': 'Allen Armold', 'JF-15490': 'Jeremy Farry', 'SF-20200': 'Sarah Foster', 'SF-20965': 'Sylvia Foulston', 'SS-20875': 'Sung Shariari', 'SC-20050': 'Sample Company A', 'RW-19690': 'Robert Waldorf', 'MS-17710': 'Maurice Satty', 'NM-18520': 'Neoma Murray', 'LW-16825': 'Laurel Workman', 'JK-16120': 'Julie Kriz', 'TS-21370': 'Todd Sumrall', 'RD-19480': 'Rick Duston', 'MM-17920': 'Michael Moore', 'FM-14215': 'Filia McAdams', 'RP-19855': 'Roy Phan', 'JF-15565': 'Jill Fjeld', 'LW-17215': 'Luke Weiss', 'TB-21625': 'Trudy Brown', 'AW-10930': 'Arthur Wiediger', 'MV-17485': 'Mark Van Huff', 'SM-20320': 'Sean Miller', 'KN-16705': 'Kristina Nunn', 'TC-21295': 'Toby Carlisle', 'NC-18535': 'Nick Crebassa', 'DK-12895': 'Dana Kaydos', 'AG-10270': 'Alejandro Grove', 'LC-16930': 'Linda Cazamias', 'ON-18715': 'Odella Nelson', 'CS-12400': 'Christopher Schild', 'TT-21070': 'Ted Trevino', 'MJ-17740': 'Max Jones', 'MP-17470': 'Mark Packer', 'JH-15985': 'Joseph Holt', 'DB-13120': 'David Bremer', 'KH-16690': 'Kristen Hastings', 'SH-20395': 'Shahid Hopkins', 'LF-17185': 'Luke Foster', 'NF-18385': 'Natalie Fritzler', 'FP-14320': 'Frank Preis', 'DV-13465': 'Dianna Vittorini', 'TP-21130': 'Theone Pippenger', 'FM-14380': 'Fred McMath', 'SC-20695': 'Steve Chapman', 'RF-19735': 'Roland Fjeld', 'CP-12340': 'Christine Phan', 'BV-11245': 'Benjamin Venier', 'DL-12865': 'Dan Lawera', 'BM-11785': 'Bryan Mills', 'LT-17110': 'Liz Thompson', 'BK-11260': 'Berenike Kampe', 'KH-16360': 'Katherine Hughes', 'MG-17650': 'Matthew Grinstein', 'FO-14305': 'Frank Olsen', 'HR-14830': 'Harold Ryan', 'LP-17095': 'Liz Preis', 'CP-12085': 'Cathy Prescott', 'AB-10255': 'Alejandro Ballentine', 'KT-16465': 'Kean Takahito', 'JW-15220': 'Jane Waco', 'DP-13390': 'Dennis Pardue', 'NS-18505': 'Neola Schneider', 'CD-12790': 'Cynthia Delaney', 'ED-13885': 'Emily Ducich', 'IL-15100': 'Ivan Liston', 'DB-13555': 'Dorothy Badders', 'DB-13405': 'Denny Blanton', 'MW-18220': 'Mitch Webber', 'AF-10870': 'Art Ferguson', 'LS-17200': 'Luke Schmidt', 'TT-21220': 'Thomas Thornton', 'FH-14350': 'Fred Harton', 'GA-14515': 'George Ashbrook', 'JP-15460': 'Jennifer Patt', 'TS-21505': 'Tony Sayre', 'NC-18415': 'Nathan Cano', 'KE-16420': 'Katrina Edelman', 'TS-21655': 'Trudy Schmidt', 'PO-18865': "Patrick O'Donnell", 'JM-15265': 'Janet Molinari', 'PS-18970': 'Paul Stevenson', 'GZ-14470': 'Gary Zandusky', 'DK-13090': 'Dave Kipp', 'BS-11755': 'Bruce Stewart', 'CC-12670': 'Craig Carreira', 'NM-18445': 'Nathan Mautz', 'DJ-13510': 'Don Jones', 'JE-15475': 'Jeremy Ellison', 'JF-15415': 'Jennifer Ferguson', 'AS-10240': 'Alan Shonely', 'AR-10825': 'Anthony Rawles', 'TH-21235': 'Tiffany House', 'MC-17845': 'Michael Chen', 'AB-10165': 'Alan Barnes', 'CK-12760': 'Cyma Kinney', 'DP-13105': 'Dave Poirier', 'AJ-10780': 'Anthony Jacobs', 'LS-16945': 'Linda Southworth', 'DL-12925': 'Daniel Lacy', 'HR-14770': 'Hallie Redmond', 'SN-20560': 'Skye Norling', 'CC-12100': 'Chad Cunningham', 'PV-18985': 'Paul Van Hugh', 'KT-16480': 'Kean Thornton', 'NP-18700': 'Nora Preis', 'GM-14500': 'Gene McClure', 'TB-21355': 'Todd Boyes', 'QJ-19255': 'Quincy Jones', 'MG-17890': 'Michael Granlund', 'SG-20470': 'Sheri Gordon', 'MC-17275': 'Marc Crier', 'BS-11380': 'Bill Stewart', 'CD-12280': 'Christina DeMoss', 'JK-15205': 'Jamie Kunitz', 'ML-17755': 'Max Ludwig', 'BE-11455': 'Brad Eason', 'PJ-18835': 'Patrick Jones', 'SV-20935': 'Susan Vittorini', 'CV-12295': 'Christina VanderZanden', 'SG-20605': 'Speros Goranitis', 'JF-15295': 'Jason Fortune-', 'DR-12940': 'Daniel Raglin', 'DM-13345': 'Denise Monton', 'CC-12475': 'Cindy Chapman', 'JO-15145': "Jack O'Briant", 'DB-12970': 'Darren Budd', 'SP-20920': 'Susan Pistek', 'NR-18550': 'Nick Radford', 'MH-17290': 'Marc Harrigan', 'FC-14245': 'Frank Carlisle', 'VP-21760': 'Victoria Pisteka', 'CM-12715': 'Craig Molinari', 'AA-10480': 'Andrew Allen', 'TW-21025': 'Tamara Willingham', 'DB-13060': 'Dave Brooks', 'JK-15640': 'Jim Kriz', 'AM-10360': 'Alice McCarthy', 'FH-14365': 'Fred Hopkins', 'GK-14620': 'Grace Kelly', 'DO-13435': 'Denny Ordway', 'EB-13705': 'Ed Braxton', 'MY-17380': 'Maribeth Yedwab', 'ME-17725': 'Max Engle', 'SC-20305': 'Sean Christensen', 'SR-20740': 'Steven Roelle', 'TH-21550': 'Tracy Hopkins', 'RS-19765': 'Roland Schwarz', 'CK-12325': 'Christine Kargatis', 'RP-19270': 'Rachel Payne', 'TS-21340': 'Toby Swindell', 'NF-18595': 'Nicole Fjeld', 'DL-13495': 'Dionis Lloyd', 'ST-20530': 'Shui Tom', 'PW-19030': 'Pauline Webber', 'JM-15655': 'Jim Mitchum', 'DB-13270': 'Deborah Brumfield', 'PN-18775': 'Parhena Norris', 'TT-21460': 'Tonja Turnell', 'CC-12685': 'Craig Carroll', 'BF-10975': 'Barbara Fisher', 'AS-10225': 'Alan Schoenberger', 'CB-12415': 'Christy Brittain', 'RH-19510': 'Rick Huthwaite', 'CC-12610': 'Corey Catlett', 'ML-17410': 'Maris LaWare', 'AZ-10750': 'Annie Zypern', 'PW-19240': 'Pierre Wener', 'DB-12910': 'Daniel Byrd', 'KD-16615': 'Ken Dana', 'JM-15865': 'John Murray', 'BO-11350': 'Bill Overfelt', 'MA-17995': 'Michelle Arnett', 'JL-15130': 'Jack Lebron', 'PR-18880': 'Patrick Ryan', 'LR-17035': 'Lisa Ryan', 'SS-20410': 'Shahid Shariari', 'SB-20185': 'Sarah Brown', 'BG-11035': 'Barry Gonzalez', 'DN-13690': 'Duane Noonan', 'JS-15685': 'Jim Sink', 'AD-10180': 'Alan Dominguez', 'TS-21610': 'Troy Staebel', 'SG-20080': 'Sandra Glassco', 'NK-18490': 'Neil Knudson', 'RM-19675': 'Robert Marley', 'VM-21685': 'Valerie Mitchum', 'MS-17980': 'Michael Stewart', 'DW-13480': 'Dianna Wilson', 'AH-10210': 'Alan Hwang', 'JL-15850': 'John Lucas', 'DB-13615': 'Doug Bickford', 'MK-18160': 'Mike Kennedy', 'TN-21040': 'Tanja Norvell', 'MH-17785': 'Maya Herman', 'CW-11905': 'Carl Weiss', 'RO-19780': "Rose O'Brian", 'LS-17245': 'Lynn Smith', 'CC-12145': 'Charles Crestani', 'MO-17800': "Meg O'Connel", 'JO-15550': 'Jesus Ocampo', 'GM-14440': 'Gary McGarr', 'HL-15040': 'Hunter Lopez', 'LW-16990': 'Lindsay Williams', 'AS-10630': 'Ann Steele', 'CY-12745': 'Craig Yedwab', 'PS-19045': 'Penelope Sewall', 'AA-10315': 'Alex Avila', 'GM-14680': 'Greg Matthias', 'MC-17575': 'Matt Collins', 'FG-14260': 'Frank Gastineau', 'GM-14455': 'Gary Mitchum', 'NH-18610': 'Nicole Hansen', 'YS-21880': 'Yana Sorensen', 'TB-21280': 'Toby Braunhardt', 'SC-20230': 'Scot Coram', 'JD-16015': 'Joy Daniels', 'KA-16525': 'Kelly Andreada', 'TC-20980': 'Tamara Chand', 'BS-11665': 'Brian Stugart', 'RH-19600': 'Rob Haberlin', 'JK-15625': 'Jim Karlsson', 'HG-15025': 'Hunter Glantz', 'JP-16135': 'Julie Prescott', 'VF-21715': 'Vicky Freymann', 'CC-12370': 'Christopher Conant', 'TC-21475': 'Tony Chapman', 'EB-14110': 'Eugene Barchas', 'AH-10030': 'Aaron Hawkins', 'MH-17455': 'Mark Hamilton', 'MF-18250': 'Monica Federle', 'HE-14800': 'Harold Engle', 'HP-14815': 'Harold Pawlan', 'EB-13870': 'Emily Burns', 'BS-11590': 'Brendan Sweed', 'KD-16345': 'Katherine Ducich', 'RC-19960': 'Ryan Crowe', 'PF-19165': 'Philip Fox', 'DW-13585': 'Dorothy Wardle', 'MG-17680': 'Maureen Gastineau', 'NP-18670': 'Nora Paige', 'MZ-17515': 'Mary Zewe', 'CA-12310': 'Christine Abelman', 'JO-15280': "Jas O'Carroll", 'KW-16435': 'Katrina Willman', 'MM-18280': 'Muhammed MacIntyre', 'MV-18190': 'Mike Vittorini', 'RF-19840': 'Roy Französisch', 'PB-19150': 'Philip Brown', 'MT-18070': 'Michelle Tran', 'KB-16240': 'Karen Bern', 'BD-11500': 'Bradley Drucker', 'OT-18730': 'Olvera Toch', 'TG-21640': 'Trudy Glocke', 'BD-11725': 'Bruce Degenhardt', 'SP-20545': 'Sibella Parks', 'PO-19195': 'Phillina Ober', 'MC-18130': 'Mike Caudle', 'EM-14095': 'Eudokia Martin', 'LL-16840': 'Lauren Leatherbury', 'JM-15535': 'Jessica Myrick', 'KC-16255': 'Karen Carlisle', 'MT-17815': 'Meg Tillman', 'BT-11395': 'Bill Tyler', 'CA-12055': 'Cathy Armstrong', 'PF-19225': 'Phillip Flathmann', 'TC-21535': 'Tracy Collins', 'MN-17935': 'Michael Nguyen', 'AS-10045': 'Aaron Smayling', 'HA-14905': 'Helen Abelman', 'SC-20440': 'Shaun Chance', 'MC-17425': 'Mark Cousins', 'MB-18085': 'Mick Brown', 'CM-12655': 'Corinna Mitchell', 'GH-14425': 'Gary Hwang', 'AB-10150': 'Aimee Bixby', 'JW-15955': 'Joni Wasserman', 'JL-15235': 'Janet Lee', 'EH-14005': 'Erica Hernandez', 'BW-11200': 'Ben Wallace', 'SW-20245': 'Scot Wooten', 'PB-18805': 'Patrick Bzostek', 'BF-11005': 'Barry Franz', 'TP-21415': 'Tom Prescott', 'BM-11575': 'Brendan Murry', 'NL-18310': 'Nancy Lomonaco', 'RR-19525': 'Rick Reed', 'MH-18025': 'Michelle Huthwaite', 'CA-11965': 'Carol Adams', 'HG-14845': 'Harry Greene', 'BP-11155': 'Becky Pak', 'AY-10555': 'Andy Yotov', 'JG-15310': 'Jason Gross', 'SJ-20215': 'Sarah Jordon', 'CM-11815': 'Candace McMahon', 'RD-19930': "Russell D'Ascenzo", 'FC-14335': 'Fred Chung', 'DH-13675': 'Duane Huffman', 'TP-21565': 'Tracy Poddar', 'DO-13645': "Doug O'Connell", 'DV-13045': 'Darrin Van Huff', 'SF-20065': 'Sandra Flanagan', 'LE-16810': 'Laurel Elliston', 'JH-15910': 'Jonathan Howell', 'RC-19825': 'Roy Collins', 'AG-10525': 'Andy Gerbode', 'VB-21745': 'Victoria Brennan', 'JG-15805': 'John Grady', 'SS-20590': 'Sonia Sunley', 'CM-12385': 'Christopher Martinez', 'AJ-10945': 'Ashley Jarboe', 'EG-13900': 'Emily Grady', 'PJ-19015': 'Pauline Johnson', 'CM-12445': 'Chuck Magee', 'JR-16210': 'Justin Ritter', 'BE-11335': 'Bill Eplett', 'CG-12040': 'Catherine Glotzbach', 'TZ-21580': 'Tracy Zic', 'JS-15880': 'John Stevenson', 'DE-13255': 'Deanra Eno', 'AT-10435': 'Alyssa Tate', 'BT-11530': 'Bradley Talbott', 'BT-11305': 'Beth Thompson', 'CS-12505': 'Cindy Stewart', 'AR-10540': 'Andy Reiter', 'SW-20455': 'Shaun Weien', 'RM-19375': 'Raymond Messe', 'BD-11770': 'Bryan Davis', 'TB-21175': 'Thomas Boland', 'NC-18625': 'Noah Childs', 'TG-21310': 'Toby Gnade', 'RS-19420': 'Ricardo Sperren', 'GM-14695': 'Greg Maxwell', 'LO-17170': 'Lori Olson', 'EN-13780': 'Edward Nazzal', 'TA-21385': 'Tom Ashbrook', 'SR-20425': 'Sharelle Roach', 'DM-12955': 'Dario Medina', 'RE-19450': 'Richard Eichhorn', 'KB-16405': 'Katrina Bavinger', 'LC-17050': 'Liz Carlisle', 'VT-21700': 'Valerie Takahito', 'KM-16660': 'Khloe Miller', 'DD-13570': 'Dorothy Dickinson', 'AG-10330': 'Alex Grayson', 'DM-13525': 'Don Miller', 'MH-17440': 'Mark Haberlin', 'ZD-21925': 'Zuschuss Donatelli', 'KB-16600': 'Ken Brennan', 'JC-16105': 'Julie Creighton', 'JB-15925': 'Joni Blumstein', 'AH-10195': 'Alan Haines', 'AS-10285': 'Alejandro Savely', 'JS-15940': 'Joni Sundaresam', 'MG-18145': 'Mike Gockenbach', 'DK-12985': 'Darren Koutras', 'LP-17080': 'Liz Pelletier', 'RB-19570': 'Rob Beeghly', 'DJ-13630': 'Doug Jacobs', 'YC-21895': 'Yoseph Carroll', 'RH-19495': 'Rick Hansen', 'JS-15595': 'Jill Stevenson', 'RK-19300': 'Ralph Kennedy', 'BS-11800': 'Bryan Spruell', 'RA-19945': 'Ryan Akin', 'VG-21790': 'Vivek Gonzalez', 'DG-13300': 'Deirdre Greer', 'BD-11620': 'Brian DeCherney', 'DW-13540': 'Don Weiss', 'SW-20755': 'Steven Ward', 'BG-11695': 'Brooke Gillingham', 'EJ-14155': 'Eva Jacobs', 'AB-10600': 'Ann Blume', 'Co-12640': 'Corey-Lock', 'NG-18430': 'Nathan Gelder', 'PL-18925': 'Paul Lucas', 'AW-10840': 'Anthony Witt', 'DA-13450': 'Dianna Arnett', 'ND-18460': 'Neil Ducich', 'GW-14605': 'Giulietta Weimer', 'AC-10450': 'Amy Cox', 'MD-17860': 'Michael Dominguez', 'DB-13660': 'Duane Benoit', 'EH-13990': 'Erica Hackney', 'JH-15820': 'John Huston', 'CM-12235': 'Chris McAfee', 'KN-16450': 'Kean Nguyen', 'CL-12700': 'Craig Leslie', 'SC-20680': 'Steve Carroll', 'DL-13330': 'Denise Leinenbach', 'BF-11215': 'Benjamin Farhat', 'CS-11845': 'Cari Sayre', 'DW-13195': 'David Wiener', 'EH-14185': 'Evan Henry', 'CS-12490': 'Cindy Schnelling', 'MF-17665': 'Maureen Fritzler', 'VM-21835': 'Vivian Mathis', 'EJ-13720': 'Ed Jacobs', 'BS-11365': 'Bill Shonely', 'CD-11920': 'Carlos Daly', 'TH-21115': 'Thea Hudgings', 'JK-16090': 'Juliana Krohn', 'HM-14980': 'Henry MacAllister', 'RB-19705': 'Roger Barcio', 'PA-19060': 'Pete Armstrong', 'JE-16165': 'Justin Ellison', 'CS-12130': 'Chad Sievert', 'SJ-20500': 'Shirley Jackson', 'GT-14755': 'Guy Thornton', 'AR-10405': 'Allen Rosenblatt', 'JG-15115': 'Jack Garza', 'KC-16675': 'Kimberly Carter', 'TB-21595': 'Troy Blackwell', 'LM-17065': 'Liz MacKendrick', 'EB-13840': 'Ellis Ballard', 'AR-10510': 'Andrew Roberts', 'ES-14020': 'Erica Smith', 'TR-21325': 'Toby Ritter', 'JL-15175': 'James Lanier', 'AF-10885': 'Art Foster', 'PM-19135': 'Peter McVee', 'SW-20275': 'Scott Williamson', 'SL-20155': 'Sara Luxemburg', 'AG-10390': 'Allen Goldenen', 'JH-15430': 'Jennifer Halladay', 'EB-14170': 'Evan Bailliet', 'LD-17005': 'Lisa DeCherney', 'CM-12115': 'Chad McGuire', 'NP-18685': 'Nora Pelletier', 'JD-15790': 'John Dryer', 'CL-11890': 'Carl Ludwig', 'IG-15085': 'Ivan Gibson', 'JW-16075': 'Julia West', 'CM-12190': 'Charlotte Melton', 'EB-13930': 'Eric Barreto', 'BT-11440': 'Bobby Trafton', 'EM-13810': 'Eleni McCrary', 'SC-20575': 'Sonia Cooley', 'MC-17635': 'Matthew Clasen', 'SB-20170': 'Sarah Bern', 'JB-16045': 'Julia Barnett', 'MG-17875': 'Michael Grace', 'JB-16000': 'Joy Bell-', 'MG-17695': 'Maureen Gnade', 'CS-12175': 'Charles Sheldon', 'AH-10465': 'Amy Hunt', 'CR-12820': 'Cyra Reiten', 'TS-21430': 'Tom Stivers', 'JM-15580': 'Jill Matthias', 'VS-21820': 'Vivek Sundaresam', 'LC-16960': 'Lindsay Castell', 'HD-14785': 'Harold Dahlen', 'Dl-13600': 'Dorris liebe', 'BB-10990': 'Barry Blumstein', 'JD-16060': 'Julia Dunbar', 'GD-14590': 'Giulietta Dortch', 'CD-11980': 'Carol Darley', 'BN-11470': 'Brad Norvell', 'MR-17545': 'Mathew Reese', 'LH-17020': 'Lisa Hazard', 'SM-20005': 'Sally Matthias', 'JJ-15445': 'Jennifer Jackson', 'EB-13975': 'Erica Bern', 'CS-12460': 'Chuck Sachs', 'VG-21805': 'Vivek Grady', 'TH-21100': 'Thea Hendricks', 'HZ-14950': 'Henia Zydlo', 'ME-18010': 'Michelle Ellison', 'BP-11230': 'Benjamin Patterson', 'BF-11080': 'Bart Folk', 'MM-17260': 'Magdelene Morse', 'MH-17620': 'Matt Hagelstein', 'MZ-17335': 'Maria Zettner', 'CR-12580': 'Clay Rozendal', 'CM-12160': 'Charles McCrossin', 'DF-13135': 'David Flashing', 'MS-17530': 'MaryBeth Skach', 'AC-10660': 'Anna Chung', 'RB-19645': 'Robert Barroso', 'SW-20350': 'Sean Wendt', 'EC-14050': 'Erin Creighton', 'PT-19

In [16]:
# check for any other null Customer Name

df[df['Customer Name'].isna()]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
6505,6506,CA-2016-152331,6/26/2016,6/30/2016,Standard Class,LD-16855,NaN,Corporate,United States,Chicago,...,60653.0,Central,OFF-AR-10001547,Office Supplies,Art,Newell 311,5.304,3.0,0.2,0.4641

In [17]:
# df = df.dropna(subset=['Customer Name'])

In [18]:
z = df[df['Ship Date'].isna()]

# z.value_counts(['Customer ID' , 'City']).head(100)
# df[df['Customer ID'] == 'JM-15265']

In [19]:
(df['Order Date'] > df['Ship Date']).sum()

np.int64(1653)

In [20]:
# df.loc[df['Postal Code'].isnull()]
# df.loc[df['City'] == 'TAMPA']

# cities = list(df['City'].unique())

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 10030 entries, 0 to 10063
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10030 non-null  int64
 1   Order ID       10030 non-null  str
 2   Order Date     10030 non-null  str
 3   Ship Date      9929 non-null   str
 4   Ship Mode      10030 non-null  str
 5   Customer ID    10030 non-null  str
 6   Customer Name  10029 non-null  str
 7   Segment        10030 non-null  str
 8   Country        10030 non-null  str
 9   City           10030 non-null  str
 10  State          10030 non-null  str
 11  Postal Code    10030 non-null  str
 12  Region         10030 non-null  str
 13  Product ID     10030 non-null  str
 14  Category       10030 non-null  str
 15  Sub-Category   10030 non-null  str
 16  Product Name   10030 non-null  str
 17  Sales          9830 non-null   float64
 18  Quantity       9831 non-null   float64
 19  Discount       10030 non-null  float64
 20  Profit         10030 non-null  float64
dtypes: float64(4), int64(1), str(16)
memory usage: 1.9 MB

**standardise mixed date formats**

In [22]:
# Convert date from string into datetime

df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='mixed')

In [23]:
# check the date type 
df[['Order Date', 'Ship Date']].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [24]:
df[df['Order Date'] > df['Ship Date']]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1562,1563,US-2017-102890,2017-06-30,2010-01-01,Same Day,SG-20470,Sheri Gordon,Consumer,United States,New York City,...,10011.0,East,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,5.0,0.4,-295.9785
2517,2518,CA-2017-123134,2017-05-02,2010-01-01,Standard Class,DW-13585,Dorothy Wardle,Corporate,United States,Westfield,...,7090.0,East,FUR-FU-10003975,Furniture,Furnishings,Eldon Advantage Chair Mats for Low to Medium P...,129.930,3.0,0.0,12.9930
3279,3280,CA-2014-102988,2014-04-05,2010-01-01,Second Class,GM-14695,Greg Maxwell,Corporate,United States,Alexandria,...,22304.0,South,OFF-AR-10000127,Office Supplies,Art,Newell 321,22.960,7.0,0.0,6.6584
4939,4940,CA-2014-157147,2014-01-13,2010-01-01,Standard Class,BD-11605,Brian Dahlen,Consumer,United States,San Francisco,...,94109.0,West,OFF-AR-10003514,Office Supplies,Art,4009 Highlighters by Sanford,19.900,5.0,0.0,6.5670
7099,7100,CA-2015-124933,2015-12-26,2010-01-01,Second Class,DF-13135,David Flashing,Consumer,United States,New York City,...,10009.0,East,OFF-PA-10003302,Office Supplies,Paper,Xerox 1906,212.640,6.0,0.0,99.9408
9101,9102,CA-2015-163181,2015-11-07,2010-01-01,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Houston,...,77041.0,Central,OFF-AR-10001683,Office Supplies,Art,Lumber Crayons,23.640,3.0,0.2,5.3190
10010,6753,CA-2016-154767,2016-06-28,2010-01-01,Second Class,BP-11155,Becky Pak,Consumer,United States,Paterson,...,7501.0,East,OFF-PA-10003039,Office Supplies,Paper,Xerox 1960,61.960,2.0,0.0,27.8820
10033,9240,CA-2017-110310,2017-10-27,2010-01-01,First Class,NB-18655,Nona Balk,Corporate,United States,Tallahassee,...,32303.0,South,OFF-PA-10001685,Office Supplies,Paper,Easy-staple paper,56.784,7.0,0.2,20.5842

**fix date Same Day**

In [25]:
df.loc[df["Ship Mode"] == 'Same Day', 'Ship Date'] = df['Order Date']

In [26]:
df['Ship Mode'].value_counts()

Ship Mode
Standard Class    6020
Second Class      1933
First Class       1539
Same Day           538
Name: count, dtype: int64

In [27]:
df['Ship Mode'].unique()

<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

In [28]:
df["Ship Duration"] = df['Ship Date'] - df["Order Date"]

In [29]:
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Ship Duration
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136,3 days
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820,3 days
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714,4 days
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310,7 days
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164,7 days
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7.0,0.00,14.1694,5 days
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4.0,0.00,1.9656,5 days
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6.0,0.20,90.7152,5 days
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3.0,0.20,5.7825,5 days
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5.0,0.00,34.4700,5 days

**Fix the dates inconsistencies**

In [30]:
mode_dict = (
    df.value_counts(['Ship Mode', 'Ship Duration']).reset_index().drop_duplicates('Ship Mode').set_index('Ship Mode')['Ship Duration'].to_dict()
    )

wrong_date_idx = df.loc[(df['Order Date'] > df['Ship Date']) | (df['Ship Date'].isna())].index

for i in wrong_date_idx:
    if df.at[i, 'Ship Mode'] in mode_dict:
        df.at[i, 'Ship Date'] = (
            df.at[i, 'Order Date']
            + mode_dict[df.at[i, 'Ship Mode']]
        )


df.info()

<class 'pandas.DataFrame'>
Index: 10030 entries, 0 to 10063
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10030 non-null  int64
 1   Order ID       10030 non-null  str
 2   Order Date     10030 non-null  datetime64[us]
 3   Ship Date      10030 non-null  datetime64[us]
 4   Ship Mode      10030 non-null  str
 5   Customer ID    10030 non-null  str
 6   Customer Name  10029 non-null  str
 7   Segment        10030 non-null  str
 8   Country        10030 non-null  str
 9   City           10030 non-null  str
 10  State          10030 non-null  str
 11  Postal Code    10030 non-null  str
 12  Region         10030 non-null  str
 13  Product ID     10030 non-null  str
 14  Category       10030 non-null  str
 15  Sub-Category   10030 non-null  str
 16  Product Name   10030 non-null  str
 17  Sales          9830 non-null   float64
 18  Quantity       9831 non-null   float64
 19  Discount       10030 non-null  float64
 20  Profit         10030 non-null  float64
 21  Ship Duration  9935 non-null   timedelta64[us]
dtypes: datetime64[us](2), float64(4), int64(1), str(14), timedelta64[us](1)
memory usage: 2.0 MB

**Check if there is any Product with wrong Product ID**

In [32]:
# df.loc[(df['Discount'] == 0) & (df['Product ID'].notna())]

mode_dict = (
    df.value_counts(['Product ID', 'Product Name']).reset_index().drop_duplicates('Product ID').set_index('Product ID')['Product Name'].to_dict()
    )

z = 0
for i in df.index:
    product_ID = df.at[i, 'Product ID']
    if (product_ID in mode_dict) and (mode_dict[product_ID] != df.at[i, 'Product Name']):
        z +=1


print(z)
# mode_dict
# df.count()
# df[df['Product ID'] == 'OFF-AR-10002833']

130

**Hash customer name via library hashlib SHA-256**

In [ ]:

#rest of null Custome Names to 'Unknown'

df.loc[df['Customer Name'].isna(), 'Customer Name'] = 'Unknown'

In [55]:
df['Customer Name'] = df['Customer Name'].apply(
    lambda x: hashlib.sha256(x.encode()).hexdigest()
)